### ISSUE TITLE
Colour wrongly applied to text instead of background in some cases

### ISSUE THREAD

**Issue by ygra** [mueschel/OsmDestinationToSVG#2]
Cf. http://osm.mueschelsoft.de/destinations/example/sandbox.htm#country=DE&tags=destination:lanes=Herrenberg;Rottenburg;Kliniken;Universit%C3%A4t|Herrenberg;Rottenburg;Kliniken;Universit%C3%A4t|Stuttgart;Reutlingen;Zentrum%0Adestination:ref:to:lanes=A81|A81|%0Adestination:ref:lanes=B28|B28|B28%0Adestination:symbol:to:lanes=motorway|motorway|%0Adestination:symbol:lanes=;;hospital;;camping_site|;;hospital;;camping_site|%0Aoneway=yes%0Aturn:lanes=left|left|through;right%0Adestination:colour=none;none;white;white|none;none;white;white|none;none;white%0Adestination:arrow:lanes=left|left|right

which is my attempt at recreating this sign:

![image](https://user-images.githubusercontent.com/1692688/144126569-fd01b0cd-7dbe-46be-b082-15a42a259cff.png)

"Universität" should have white background, not foreground, and I think the tagging to be correct.

(There's also the issue of the icon not being applied to the correct line, but perhaps that's a missing feature here; I think the tagging for that is correct as well.)

**Comment by mueschel** [comment]
Hi,
there are two issues here: 
- "destination:colour" misses the ':lanes' Suffix. Without it, '|' has no special meaning and the background color is set to "white|none" which doesn't make sense and trips up the automatic selection of the text color.

- In my interpreter, symbols and destinations are only matched when both have the exact same number of entries. The symbols have one extra entry for the camp ground, so that the destinations would need an empty, dummy entry:

http://osm.mueschelsoft.de/destinations/example/sandbox.htm#country=DE&tags=destination:lanes=Herrenberg;Rottenburg;Kliniken;Universit%C3%A4t;|Herrenberg;Rottenburg;Kliniken;Universit%C3%A4t;|Stuttgart;Reutlingen;Zentrum%0Adestination:ref:to:lanes=A81|A81|%0Adestination:ref:lanes=B28|B28|B28%0Adestination:symbol:to:lanes=motorway|motorway|%0Adestination:symbol:lanes=;;hospital;;camping_site|;;hospital;;camping_site|%0Aoneway=yes%0Aturn:lanes=left|left|through;right%0Adestination:colour:lanes=none;none;white;white|none;none;white;white|none;none;white%0Adestination:arrow:lanes=left|left|right

**Comment by ygra** [comment]
Ah, thanks. All that is probably somewhat ill-specified with few implementations at all. I'll keep those limitations in mind for future signs :)
